runtime: java21
instance_class: F2

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

liveness_check:
  path: "/actuator/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 1

readiness_check:
  path: "/actuator/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 1
  app_start_timeout_sec: 60
