apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cloud
  labels:
    app: hello-cloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-cloud
  template:
    metadata:
      labels:
        app: hello-cloud
    spec:
      containers:
        - name: hello-cloud
          image: gcr.io/PROJECT_ID/hello-cloud:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "gcp"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: hello-cloud-service
spec:
  type: LoadBalancer
  selector:
    app: hello-cloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
